import { createRouter, createWebHistory } from 'vue-router'

declare global {
  interface Window {
    __ERP_BOOTSTRAP__?: {
      ui?: {
        basePath?: string
      }
    }
  }
}

const basePath = window.__ERP_BOOTSTRAP__?.ui?.basePath ?? '/'

export const router = createRouter({
  history: createWebHistory(basePath),
  routes: [
    { path: '/', redirect: '/home' },
    { path: '/login', name: 'login', component: () => import('../pages/login/LoginPage.vue') },
    {
      path: '/',
      component: () => import('../layouts/DefaultLayout.vue'),
      children: [
        { path: 'home', name: 'home', component: () => import('../pages/home/HomePage.vue') },
        {
          path: 'notas/emitidas',
          name: 'notas-emitidas',
          component: () => import('../pages/notas/EmitidasPage.vue'),
          meta: { breadcrumbs: ['NFS-e', 'Emitidas'] },
        },
        {
          path: 'notas/recebidas',
          name: 'notas-recebidas',
          component: () => import('../pages/notas/RecebidasPage.vue'),
          meta: { breadcrumbs: ['NFS-e', 'Recebidas'] },
        },
        {
          path: 'notas/rascunhos',
          name: 'notas-rascunhos',
          component: () => import('../pages/notas/RascunhosPage.vue'),
          meta: { breadcrumbs: ['NFS-e', 'Rascunhos'] },
        },
        {
          path: 'notas/visualizar/:id',
          name: 'notas-visualizar',
          component: () => import('../pages/notas/VisualizarPage.vue'),
          meta: { breadcrumbs: ['NFS-e', 'Visualizar'] },
        },
        { path: 'perfil/configuracao', name: 'perfil-configuracao', component: () => import('../pages/perfil/ConfiguracaoPage.vue') },
        {
          path: 'perfil/servicos-favoritos',
          name: 'perfil-servicos-favoritos',
          component: () => import('../pages/perfil/ServicosFavoritosPage.vue'),
        },
        {
          path: 'dps/pessoas',
          name: 'dps-pessoas',
          component: () => import('../pages/dps/PessoasPage.vue'),
          meta: { breadcrumbs: [{ label: 'Emissão Completa', to: '/dps/pessoas' }, 'Pessoas'] },
        },
        { path: 'dps/simplificada', name: 'dps-simplificada', component: () => import('../pages/dps/SimplificadaPage.vue') },
        { path: 'dps/bypass', name: 'dps-bypass', component: () => import('../pages/dps/BypassPage.vue') },
        { path: 'dps/servico', name: 'dps-servico', component: () => import('../pages/dps/ServicoPage.vue') },

        {
          path: 'produtos',
          name: 'produtos',
          component: () => import('../pages/produtos/ProdutosListaPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Produtos'], title: 'Produtos' },
        },
        {
          path: 'produtos/novo',
          name: 'produtos-novo',
          component: () => import('../pages/produtos/ProdutoNovoPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Produtos', 'Novo'], title: 'Novo produto' },
        },
        {
          path: 'produtos/:id/editar',
          name: 'produtos-editar',
          component: () => import('../pages/produtos/ProdutoEditarPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Produtos', 'Editar'], title: 'Editar produto' },
        },
        {
          path: 'produtos/:id',
          name: 'produtos-visualizar',
          component: () => import('../pages/produtos/ProdutoVisualizarPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Produtos', 'Visualizar'], title: 'Visualizar produto' },
        },
        {
          path: 'produtos/categorias',
          name: 'categorias-produto',
          component: () => import('../pages/produtos/categorias/CategoriasProdutoListaPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Produtos', 'Categorias'], title: 'Categorias de Produto' },
        },
        {
          path: 'produtos/categorias/novo',
          name: 'categorias-produto-novo',
          component: () => import('../pages/produtos/categorias/CategoriaProdutoNovoPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Produtos', 'Categorias', 'Novo'], title: 'Nova categoria' },
        },
        {
          path: 'produtos/categorias/:id/editar',
          name: 'categorias-produto-editar',
          component: () => import('../pages/produtos/categorias/CategoriaProdutoEditarPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Produtos', 'Categorias', 'Editar'], title: 'Editar categoria' },
        },
        {
          path: 'produtos/categorias/:id',
          name: 'categorias-produto-visualizar',
          component: () => import('../pages/produtos/categorias/CategoriaProdutoVisualizarPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Produtos', 'Categorias', 'Visualizar'], title: 'Visualizar categoria' },
        },
        {
          path: 'produtos/unidades',
          name: 'unidades-medida',
          component: () => import('../pages/produtos/unidades/UnidadesMedidaListaPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Produtos', 'Unidades de medida'], title: 'Unidades de Medida' },
        },
        {
          path: 'produtos/unidades/novo',
          name: 'unidades-medida-novo',
          component: () => import('../pages/produtos/unidades/UnidadeMedidaNovoPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Produtos', 'Unidades de medida', 'Novo'], title: 'Nova unidade' },
        },
        {
          path: 'produtos/unidades/:id/editar',
          name: 'unidades-medida-editar',
          component: () => import('../pages/produtos/unidades/UnidadeMedidaEditarPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Produtos', 'Unidades de medida', 'Editar'], title: 'Editar unidade' },
        },
        {
          path: 'produtos/unidades/:id',
          name: 'unidades-medida-visualizar',
          component: () => import('../pages/produtos/unidades/UnidadeMedidaVisualizarPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Produtos', 'Unidades de medida', 'Visualizar'], title: 'Visualizar unidade' },
        },
        {
          path: 'produtos/marcas',
          name: 'marcas',
          component: () => import('../pages/produtos/marcas/MarcasListaPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Produtos', 'Marcas'], title: 'Marcas' },
        },
        {
          path: 'produtos/marcas/novo',
          name: 'marcas-novo',
          component: () => import('../pages/produtos/marcas/MarcaNovoPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Produtos', 'Marcas', 'Novo'], title: 'Nova marca' },
        },
        {
          path: 'produtos/marcas/:id/editar',
          name: 'marcas-editar',
          component: () => import('../pages/produtos/marcas/MarcaEditarPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Produtos', 'Marcas', 'Editar'], title: 'Editar marca' },
        },
        {
          path: 'produtos/marcas/:id',
          name: 'marcas-visualizar',
          component: () => import('../pages/produtos/marcas/MarcaVisualizarPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Produtos', 'Marcas', 'Visualizar'], title: 'Visualizar marca' },
        },

        {
          path: 'servicos/categorias',
          name: 'categorias-servico',
          component: () => import('../pages/servicos/categorias/CategoriasServicoListaPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Serviços', 'Categorias'], title: 'Categorias de Serviço' },
        },
        {
          path: 'servicos/categorias/novo',
          name: 'categorias-servico-novo',
          component: () => import('../pages/servicos/categorias/CategoriaServicoNovoPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Serviços', 'Categorias', 'Novo'], title: 'Nova categoria de serviço' },
        },
        {
          path: 'servicos/categorias/:id/editar',
          name: 'categorias-servico-editar',
          component: () => import('../pages/servicos/categorias/CategoriaServicoEditarPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Serviços', 'Categorias', 'Editar'], title: 'Editar categoria de serviço' },
        },
        {
          path: 'servicos/categorias/:id',
          name: 'categorias-servico-visualizar',
          component: () => import('../pages/servicos/categorias/CategoriaServicoVisualizarPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Serviços', 'Categorias', 'Visualizar'], title: 'Visualizar categoria de serviço' },
        },

        {
          path: 'servicos',
          name: 'servicos',
          component: () => import('../pages/servicos/ServicosListaPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Serviços'], title: 'Serviços' },
        },
        {
          path: 'servicos/novo',
          name: 'servicos-novo',
          component: () => import('../pages/servicos/ServicoNovoPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Serviços', 'Novo'], title: 'Novo serviço' },
        },
        {
          path: 'servicos/:id/editar',
          name: 'servicos-editar',
          component: () => import('../pages/servicos/ServicoEditarPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Serviços', 'Editar'], title: 'Editar serviço' },
        },
        {
          path: 'servicos/:id',
          name: 'servicos-visualizar',
          component: () => import('../pages/servicos/ServicoVisualizarPage.vue'),
          meta: { breadcrumbs: ['Cadastros', 'Serviços', 'Visualizar'], title: 'Visualizar serviço' },
        },

        {
          path: 'estoque',
          name: 'estoque',
          component: () => import('../pages/estoque/EstoqueListaPage.vue'),
          meta: { breadcrumbs: ['Estoque', 'Gerenciar estoque'], title: 'Estoque' },
        },
        {
          path: 'estoque/novo',
          name: 'estoque-novo',
          component: () => import('../pages/estoque/EstoqueNovoPage.vue'),
          meta: { breadcrumbs: ['Estoque', 'Gerenciar estoque', 'Novo'], title: 'Adicionar estoque' },
        },
        {
          path: 'estoque/:id/editar',
          name: 'estoque-editar',
          component: () => import('../pages/estoque/EstoqueEditarPage.vue'),
          meta: { breadcrumbs: ['Estoque', 'Gerenciar estoque', 'Editar'], title: 'Editar estoque' },
        },
        {
          path: 'estoque/retirada',
          name: 'estoque-retirada',
          component: () => import('../pages/estoque/RetiradaEstoquePage.vue'),
          meta: { breadcrumbs: ['Estoque', 'Retirada'], title: 'Retirada de Estoque' },
        },
        {
          path: 'estoque/apontamento',
          name: 'estoque-apontamento',
          component: () => import('../pages/estoque/ApontamentoProducaoPage.vue'),
          meta: { breadcrumbs: ['Estoque', 'Apontamento'], title: 'Apontamento de Produção' },
        },

        {
          path: 'financeiro/contas-pagar',
          name: 'contas-pagar',
          component: () => import('../pages/financeiro/contasPagar/ContasPagarListaPage.vue'),
          meta: { breadcrumbs: ['Financeiro', 'Contas a pagar'], title: 'Contas a pagar' },
        },
        {
          path: 'financeiro/contas-pagar/novo',
          name: 'contas-pagar-novo',
          component: () => import('../pages/financeiro/contasPagar/ContaPagarNovoPage.vue'),
          meta: { breadcrumbs: ['Financeiro', 'Contas a pagar', 'Novo'], title: 'Nova conta a pagar' },
        },
        {
          path: 'financeiro/contas-pagar/:id/editar',
          name: 'contas-pagar-editar',
          component: () => import('../pages/financeiro/contasPagar/ContaPagarEditarPage.vue'),
          meta: { breadcrumbs: ['Financeiro', 'Contas a pagar', 'Editar'], title: 'Editar conta a pagar' },
        },
        {
          path: 'financeiro/contas-pagar/:id',
          name: 'contas-pagar-visualizar',
          component: () => import('../pages/financeiro/contasPagar/ContaPagarVisualizarPage.vue'),
          meta: { breadcrumbs: ['Financeiro', 'Contas a pagar', 'Visualizar'], title: 'Visualizar conta a pagar' },
        },

        {
          path: 'financeiro/contas-receber',
          name: 'contas-receber',
          component: () => import('../pages/financeiro/contasReceber/ContasReceberListaPage.vue'),
          meta: { breadcrumbs: ['Financeiro', 'Contas a receber'], title: 'Contas a receber' },
        },
        {
          path: 'financeiro/contas-receber/novo',
          name: 'contas-receber-novo',
          component: () => import('../pages/financeiro/contasReceber/ContaReceberNovoPage.vue'),
          meta: { breadcrumbs: ['Financeiro', 'Contas a receber', 'Novo'], title: 'Nova conta a receber' },
        },
        {
          path: 'financeiro/contas-receber/:id/editar',
          name: 'contas-receber-editar',
          component: () => import('../pages/financeiro/contasReceber/ContaReceberEditarPage.vue'),
          meta: { breadcrumbs: ['Financeiro', 'Contas a receber', 'Editar'], title: 'Editar conta a receber' },
        },
        {
          path: 'financeiro/contas-receber/:id',
          name: 'contas-receber-visualizar',
          component: () => import('../pages/financeiro/contasReceber/ContaReceberVisualizarPage.vue'),
          meta: { breadcrumbs: ['Financeiro', 'Contas a receber', 'Visualizar'], title: 'Visualizar conta a receber' },
        },

        {
          path: 'Petshop/ListaPets',
          name: 'petshop-lista-pets',
          component: () => import('../pages/petshop/animais/ListaPetsPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Lista de Pets'] },
        },
        {
          path: 'Petshop/Agenda',
          name: 'petshop-agenda-geral',
          component: () => import('../pages/petshop/agenda/AgendaGeralPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Agenda'], title: 'Agenda Geral' },
        },
        {
          path: 'Petshop/Pets/Novo',
          name: 'petshop-pets-novo',
          component: () => import('../pages/petshop/animais/PetNovoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Pets', 'Novo'] },
        },
        {
          path: 'Petshop/Pets/:id/Editar',
          name: 'petshop-pets-editar',
          component: () => import('../pages/petshop/animais/PetEditarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Pets', 'Editar'] },
        },
        {
          path: 'Petshop/Pets/:id',
          name: 'petshop-pets-visualizar',
          component: () => import('../pages/petshop/animais/PetVisualizarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Pets', 'Visualizar'] },
        },

        // Petshop - placeholders para menu
        {
          path: 'Petshop/Especies',
          name: 'petshop-especies',
          component: () => import('../pages/petshop/animais/especies/EspecieListaPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Cadastros', 'Espécies'], title: 'Espécies' },
        },
        {
          path: 'Petshop/Especies/Novo',
          name: 'petshop-especies-novo',
          component: () => import('../pages/petshop/animais/especies/EspecieNovoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Cadastros', 'Espécies', 'Novo'], title: 'Nova espécie' },
        },
        {
          path: 'Petshop/Especies/:id/Editar',
          name: 'petshop-especies-editar',
          component: () => import('../pages/petshop/animais/especies/EspecieEditarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Cadastros', 'Espécies', 'Editar'], title: 'Editar espécie' },
        },
        {
          path: 'Petshop/Especies/:id',
          name: 'petshop-especies-visualizar',
          component: () => import('../pages/petshop/animais/especies/EspecieVisualizarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Cadastros', 'Espécies', 'Visualizar'], title: 'Visualizar espécie' },
        },
        {
          path: 'Petshop/Racas',
          name: 'petshop-racas',
          component: () => import('../pages/petshop/animais/racas/RacaListaPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Cadastros', 'Raças'], title: 'Raças' },
        },
        {
          path: 'Petshop/Racas/Novo',
          name: 'petshop-racas-novo',
          component: () => import('../pages/petshop/animais/racas/RacaNovoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Cadastros', 'Raças', 'Novo'], title: 'Nova raça' },
        },
        {
          path: 'Petshop/Racas/:id/Editar',
          name: 'petshop-racas-editar',
          component: () => import('../pages/petshop/animais/racas/RacaEditarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Cadastros', 'Raças', 'Editar'], title: 'Editar raça' },
        },
        {
          path: 'Petshop/Racas/:id',
          name: 'petshop-racas-visualizar',
          component: () => import('../pages/petshop/animais/racas/RacaVisualizarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Cadastros', 'Raças', 'Visualizar'], title: 'Visualizar raça' },
        },
        {
          path: 'Petshop/Pelagens',
          name: 'petshop-pelagens',
          component: () => import('../pages/petshop/animais/pelagens/PelagemListaPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Cadastros', 'Pelagens'], title: 'Pelagens' },
        },
        {
          path: 'Petshop/Pelagens/Novo',
          name: 'petshop-pelagens-novo',
          component: () => import('../pages/petshop/animais/pelagens/PelagemNovoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Cadastros', 'Pelagens', 'Novo'], title: 'Nova pelagem' },
        },
        {
          path: 'Petshop/Pelagens/:id/Editar',
          name: 'petshop-pelagens-editar',
          component: () => import('../pages/petshop/animais/pelagens/PelagemEditarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Cadastros', 'Pelagens', 'Editar'], title: 'Editar pelagem' },
        },
        {
          path: 'Petshop/Pelagens/:id',
          name: 'petshop-pelagens-visualizar',
          component: () => import('../pages/petshop/animais/pelagens/PelagemVisualizarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Cadastros', 'Pelagens', 'Visualizar'], title: 'Visualizar pelagem' },
        },
        {
          path: 'Petshop/Planos/Usuarios',
          name: 'petshop-planos-usuarios',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Cadastros', 'Planos', 'Usuários Plano'], title: 'Usuários Plano' },
        },
        {
          path: 'Petshop/Planos/Avulso',
          name: 'petshop-planos-avulso',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Cadastros', 'Planos', 'Usuário Avulso'], title: 'Usuário Avulso' },
        },
        {
          path: 'Petshop/Vet/Cadastros/Medicos',
          name: 'petshop-vet-medicos',
          component: () => import('../pages/petshop/vet/cadastros/medicos/MedicoListaPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Médico'], title: 'Médico' },
        },
        {
          path: 'Petshop/Vet/Cadastros/Medicos/Novo',
          name: 'petshop-vet-medicos-novo',
          component: () => import('../pages/petshop/vet/cadastros/medicos/MedicoNovoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Médico', 'Novo'], title: 'Novo médico' },
        },
        {
          path: 'Petshop/Vet/Cadastros/Medicos/:id/Editar',
          name: 'petshop-vet-medicos-editar',
          component: () => import('../pages/petshop/vet/cadastros/medicos/MedicoEditarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Médico', 'Editar'], title: 'Editar médico' },
        },
        {
          path: 'Petshop/Vet/Cadastros/Medicos/:id',
          name: 'petshop-vet-medicos-visualizar',
          component: () => import('../pages/petshop/vet/cadastros/medicos/MedicoVisualizarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Médico', 'Visualizar'], title: 'Visualizar médico' },
        },
        {
          path: 'Petshop/Vet/Cadastros/SalasAtendimento',
          name: 'petshop-vet-salas-atendimento',
          component: () => import('../pages/petshop/vet/cadastros/salasAtendimento/SalaAtendimentoListaPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Salas de Atendimento'], title: 'Salas de Atendimento' },
        },
        {
          path: 'Petshop/Vet/Cadastros/SalasAtendimento/Novo',
          name: 'petshop-vet-salas-atendimento-novo',
          component: () => import('../pages/petshop/vet/cadastros/salasAtendimento/SalaAtendimentoNovoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Salas de Atendimento', 'Novo'], title: 'Nova sala' },
        },
        {
          path: 'Petshop/Vet/Cadastros/SalasAtendimento/:id/Editar',
          name: 'petshop-vet-salas-atendimento-editar',
          component: () => import('../pages/petshop/vet/cadastros/salasAtendimento/SalaAtendimentoEditarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Salas de Atendimento', 'Editar'], title: 'Editar sala' },
        },
        {
          path: 'Petshop/Vet/Cadastros/SalasAtendimento/:id',
          name: 'petshop-vet-salas-atendimento-visualizar',
          component: () => import('../pages/petshop/vet/cadastros/salasAtendimento/SalaAtendimentoVisualizarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Salas de Atendimento', 'Visualizar'], title: 'Visualizar sala' },
        },
        {
          path: 'Petshop/Vet/Cadastros/SalasInternacao',
          name: 'petshop-vet-salas-internacao',
          component: () => import('../pages/petshop/vet/cadastros/salasInternacao/SalaInternacaoListaPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Salas de Internação'], title: 'Salas de Internação' },
        },
        {
          path: 'Petshop/Vet/Cadastros/SalasInternacao/Novo',
          name: 'petshop-vet-salas-internacao-novo',
          component: () => import('../pages/petshop/vet/cadastros/salasInternacao/SalaInternacaoNovoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Salas de Internação', 'Novo'], title: 'Nova sala' },
        },
        {
          path: 'Petshop/Vet/Cadastros/SalasInternacao/:id/Editar',
          name: 'petshop-vet-salas-internacao-editar',
          component: () => import('../pages/petshop/vet/cadastros/salasInternacao/SalaInternacaoEditarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Salas de Internação', 'Editar'], title: 'Editar sala' },
        },
        {
          path: 'Petshop/Vet/Cadastros/SalasInternacao/:id',
          name: 'petshop-vet-salas-internacao-visualizar',
          component: () => import('../pages/petshop/vet/cadastros/salasInternacao/SalaInternacaoVisualizarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Salas de Internação', 'Visualizar'], title: 'Visualizar sala' },
        },
        {
          path: 'Petshop/Vet/Cadastros/Checklist',
          name: 'petshop-vet-checklist',
          component: () => import('../pages/petshop/vet/cadastros/checklist/ChecklistListaPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Checklist'], title: 'Checklist' },
        },
        {
          path: 'Petshop/Vet/Cadastros/Checklist/Novo',
          name: 'petshop-vet-checklist-novo',
          component: () => import('../pages/petshop/vet/cadastros/checklist/ChecklistNovoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Checklist', 'Novo'], title: 'Novo checklist' },
        },
        {
          path: 'Petshop/Vet/Cadastros/Checklist/:id/Editar',
          name: 'petshop-vet-checklist-editar',
          component: () => import('../pages/petshop/vet/cadastros/checklist/ChecklistEditarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Checklist', 'Editar'], title: 'Editar checklist' },
        },
        {
          path: 'Petshop/Vet/Cadastros/Checklist/:id',
          name: 'petshop-vet-checklist-visualizar',
          component: () => import('../pages/petshop/vet/cadastros/checklist/ChecklistVisualizarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Checklist', 'Visualizar'], title: 'Visualizar checklist' },
        },
        {
          path: 'Petshop/Vet/Cadastros/Alergias',
          name: 'petshop-vet-alergias',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Alergias'], title: 'Alergias' },
        },
        {
          path: 'Petshop/Vet/Cadastros/CondicoesCronicas',
          name: 'petshop-vet-condicoes-cronicas',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Condições crônicas'], title: 'Condições crônicas' },
        },
        {
          path: 'Petshop/Vet/Cadastros/Medicamentos',
          name: 'petshop-vet-medicamentos',
          component: () => import('../pages/petshop/vet/cadastros/medicamentos/MedicamentoListaPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Medicamentos'], title: 'Medicamentos' },
        },
        {
          path: 'Petshop/Vet/Cadastros/Medicamentos/Novo',
          name: 'petshop-vet-medicamentos-novo',
          component: () => import('../pages/petshop/vet/cadastros/medicamentos/MedicamentoNovoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Medicamentos', 'Novo'], title: 'Novo medicamento' },
        },
        {
          path: 'Petshop/Vet/Cadastros/Medicamentos/:id/Editar',
          name: 'petshop-vet-medicamentos-editar',
          component: () => import('../pages/petshop/vet/cadastros/medicamentos/MedicamentoEditarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Medicamentos', 'Editar'], title: 'Editar medicamento' },
        },
        {
          path: 'Petshop/Vet/Cadastros/Medicamentos/:id',
          name: 'petshop-vet-medicamentos-visualizar',
          component: () => import('../pages/petshop/vet/cadastros/medicamentos/MedicamentoVisualizarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Medicamentos', 'Visualizar'], title: 'Visualizar medicamento' },
        },
        {
          path: 'Petshop/Vet/Cadastros/Vacinas',
          name: 'petshop-vet-vacinas',
          component: () => import('../pages/petshop/vet/cadastros/vacinas/VacinaListaPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Vacinas'], title: 'Vacinas' },
        },
        {
          path: 'Petshop/Vet/Cadastros/Vacinas/Novo',
          name: 'petshop-vet-vacinas-novo',
          component: () => import('../pages/petshop/vet/cadastros/vacinas/VacinaNovoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Vacinas', 'Novo'], title: 'Nova vacina' },
        },
        {
          path: 'Petshop/Vet/Cadastros/Vacinas/:id/Editar',
          name: 'petshop-vet-vacinas-editar',
          component: () => import('../pages/petshop/vet/cadastros/vacinas/VacinaEditarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Vacinas', 'Editar'], title: 'Editar vacina' },
        },
        {
          path: 'Petshop/Vet/Cadastros/Vacinas/:id',
          name: 'petshop-vet-vacinas-visualizar',
          component: () => import('../pages/petshop/vet/cadastros/vacinas/VacinaVisualizarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Vacinas', 'Visualizar'], title: 'Visualizar vacina' },
        },
        {
          path: 'Petshop/Vet/Cadastros/ModeloAtendimento',
          name: 'petshop-vet-modelo-atendimento',
          component: () => import('../pages/petshop/vet/cadastros/modeloAtendimento/ModeloAtendimentoListaPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Modelo de Atendimento'], title: 'Modelo de Atendimento' },
        },
        {
          path: 'Petshop/Vet/Cadastros/ModeloAtendimento/Novo',
          name: 'petshop-vet-modelo-atendimento-novo',
          component: () => import('../pages/petshop/vet/cadastros/modeloAtendimento/ModeloAtendimentoNovoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Modelo de Atendimento', 'Novo'], title: 'Novo modelo de atendimento' },
        },
        {
          path: 'Petshop/Vet/Cadastros/ModeloAtendimento/:id/Editar',
          name: 'petshop-vet-modelo-atendimento-editar',
          component: () => import('../pages/petshop/vet/cadastros/modeloAtendimento/ModeloAtendimentoEditarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Modelo de Atendimento', 'Editar'], title: 'Editar modelo de atendimento' },
        },
        {
          path: 'Petshop/Vet/Cadastros/ModeloAtendimento/:id',
          name: 'petshop-vet-modelo-atendimento-visualizar',
          component: () => import('../pages/petshop/vet/cadastros/modeloAtendimento/ModeloAtendimentoVisualizarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Modelo de Atendimento', 'Visualizar'], title: 'Visualizar modelo de atendimento' },
        },
        {
          path: 'Petshop/Vet/Cadastros/ModeloAvaliacao',
          name: 'petshop-vet-modelo-avaliacao',
          component: () => import('../pages/petshop/vet/cadastros/modeloAvaliacao/ModeloAvaliacaoListaPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Modelo de Avaliação'], title: 'Modelo de Avaliação' },
        },
        {
          path: 'Petshop/Vet/Cadastros/ModeloAvaliacao/Novo',
          name: 'petshop-vet-modelo-avaliacao-novo',
          component: () => import('../pages/petshop/vet/cadastros/modeloAvaliacao/ModeloAvaliacaoNovoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Modelo de Avaliação', 'Novo'], title: 'Novo modelo de avaliação' },
        },
        {
          path: 'Petshop/Vet/Cadastros/ModeloAvaliacao/:id/Editar',
          name: 'petshop-vet-modelo-avaliacao-editar',
          component: () => import('../pages/petshop/vet/cadastros/modeloAvaliacao/ModeloAvaliacaoEditarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Modelo de Avaliação', 'Editar'], title: 'Editar modelo de avaliação' },
        },
        {
          path: 'Petshop/Vet/Cadastros/ModeloAvaliacao/:id',
          name: 'petshop-vet-modelo-avaliacao-visualizar',
          component: () => import('../pages/petshop/vet/cadastros/modeloAvaliacao/ModeloAvaliacaoVisualizarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Modelo de Avaliação', 'Visualizar'], title: 'Visualizar modelo de avaliação' },
        },
        {
          path: 'Petshop/Vet/Cadastros/ModeloPrescricao',
          name: 'petshop-vet-modelo-prescricao',
          component: () => import('../pages/petshop/vet/cadastros/modeloPrescricao/ModeloPrescricaoListaPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Modelo de Prescrição'], title: 'Modelo de Prescrição' },
        },
        {
          path: 'Petshop/Vet/Cadastros/ModeloPrescricao/Novo',
          name: 'petshop-vet-modelo-prescricao-novo',
          component: () => import('../pages/petshop/vet/cadastros/modeloPrescricao/ModeloPrescricaoNovoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Modelo de Prescrição', 'Novo'], title: 'Novo modelo de prescrição' },
        },
        {
          path: 'Petshop/Vet/Cadastros/ModeloPrescricao/:id/Editar',
          name: 'petshop-vet-modelo-prescricao-editar',
          component: () => import('../pages/petshop/vet/cadastros/modeloPrescricao/ModeloPrescricaoEditarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Modelo de Prescrição', 'Editar'], title: 'Editar modelo de prescrição' },
        },
        {
          path: 'Petshop/Vet/Cadastros/ModeloPrescricao/:id',
          name: 'petshop-vet-modelo-prescricao-visualizar',
          component: () => import('../pages/petshop/vet/cadastros/modeloPrescricao/ModeloPrescricaoVisualizarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Cadastros', 'Modelo de Prescrição', 'Visualizar'], title: 'Visualizar modelo de prescrição' },
        },
        {
          path: 'Petshop/Vet/Atendimentos',
          name: 'petshop-vet-atendimentos',
          component: () => import('../pages/petshop/vet/atendimentos/AtendimentoListaPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Operação', 'Atendimento'], title: 'Atendimento' },
        },
        {
          path: 'Petshop/Vet/Atendimentos/Novo',
          name: 'petshop-vet-atendimentos-novo',
          component: () => import('../pages/petshop/vet/atendimentos/AtendimentoNovoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Operação', 'Atendimento', 'Novo'], title: 'Novo atendimento' },
        },
        {
          path: 'Petshop/Vet/Atendimentos/:id/Editar',
          name: 'petshop-vet-atendimentos-editar',
          component: () => import('../pages/petshop/vet/atendimentos/AtendimentoEditarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Operação', 'Atendimento', 'Editar'], title: 'Editar atendimento' },
        },
        {
          path: 'Petshop/Vet/Atendimentos/:id',
          name: 'petshop-vet-atendimentos-visualizar',
          component: () => import('../pages/petshop/vet/atendimentos/AtendimentoVisualizarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Operação', 'Atendimento', 'Visualizar'], title: 'Visualizar atendimento' },
        },
        {
          path: 'Petshop/Vet/Prontuarios/Fila',
          name: 'petshop-vet-prontuarios-fila',
          component: () => import('../pages/petshop/vet/prontuarios/fila/FilaListaPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Operação', 'Prontuários', 'Fila de consultas'], title: 'Fila de consultas' },
        },
        {
          path: 'Petshop/Vet/Prontuarios/Fila/Novo',
          name: 'petshop-vet-prontuarios-fila-novo',
          component: () => import('../pages/petshop/vet/prontuarios/fila/FilaNovoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Operação', 'Prontuários', 'Fila de consultas', 'Novo'], title: 'Novo prontuário' },
        },
        {
          path: 'Petshop/Vet/Prontuarios/Fila/:id/Editar',
          name: 'petshop-vet-prontuarios-fila-editar',
          component: () => import('../pages/petshop/vet/prontuarios/fila/FilaEditarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Operação', 'Prontuários', 'Fila de consultas', 'Editar'], title: 'Editar prontuário' },
        },
        {
          path: 'Petshop/Vet/Prontuarios/Fila/:id',
          name: 'petshop-vet-prontuarios-fila-visualizar',
          component: () => import('../pages/petshop/vet/prontuarios/fila/FilaVisualizarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Operação', 'Prontuários', 'Fila de consultas', 'Visualizar'], title: 'Visualizar prontuário' },
        },
        {
          path: 'Petshop/Vet/Prontuarios/Consultas',
          name: 'petshop-vet-prontuarios-consultas',
          component: () => import('../pages/petshop/vet/prontuarios/consultas/ConsultasHistoricoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Operação', 'Prontuários', 'Histórico de Consultas'], title: 'Histórico de Consultas' },
        },
        {
          path: 'Petshop/Vet/Prontuarios/Exames',
          name: 'petshop-vet-prontuarios-exames',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Operação', 'Prontuários', 'Histórico de Exames'], title: 'Histórico de Exames' },
        },
        {
          path: 'Petshop/Vet/Prontuarios/Prescricoes',
          name: 'petshop-vet-prontuarios-prescricoes',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Operação', 'Prontuários', 'Histórico de Prescrições'], title: 'Histórico de Prescrições' },
        },
        {
          path: 'Petshop/Vet/Vacinacoes/Painel',
          name: 'petshop-vet-vacinacoes-painel',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Operação', 'Vacinações', 'Painel de vacinação'], title: 'Painel de vacinação' },
        },
        {
          path: 'Petshop/Vet/Vacinacoes/Historico',
          name: 'petshop-vet-vacinacoes-historico',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Operação', 'Vacinações', 'Histórico de Vacinas'], title: 'Histórico de Vacinas' },
        },
        {
          path: 'Petshop/Vet/Vacinacoes/Aplicar',
          name: 'petshop-vet-vacinacoes-aplicar',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Operação', 'Vacinações', 'Aplicar Vacinação'], title: 'Aplicar Vacinação' },
        },
        {
          path: 'Petshop/Vet/Internacoes/Historico',
          name: 'petshop-vet-internacoes-historico',
          component: () => import('../pages/petshop/vet/internacoes/historico/InternacaoListaPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Operação', 'Internações', 'Histórico de Internação'], title: 'Histórico de Internação' },
        },
        {
          path: 'Petshop/Vet/Internacoes/Historico/Novo',
          name: 'petshop-vet-internacoes-historico-novo',
          component: () => import('../pages/petshop/vet/internacoes/historico/InternacaoNovoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Operação', 'Internações', 'Histórico de Internação', 'Novo'], title: 'Nova internação' },
        },
        {
          path: 'Petshop/Vet/Internacoes/Historico/:id/Editar',
          name: 'petshop-vet-internacoes-historico-editar',
          component: () => import('../pages/petshop/vet/internacoes/historico/InternacaoEditarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Operação', 'Internações', 'Histórico de Internação', 'Editar'], title: 'Editar internação' },
        },
        {
          path: 'Petshop/Vet/Internacoes/Historico/:id',
          name: 'petshop-vet-internacoes-historico-visualizar',
          component: () => import('../pages/petshop/vet/internacoes/historico/InternacaoVisualizarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Operação', 'Internações', 'Histórico de Internação', 'Visualizar'], title: 'Visualizar internação' },
        },
        {
          path: 'Petshop/Vet/Internacoes/Ocupacao',
          name: 'petshop-vet-internacoes-ocupacao',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Veterinário', 'Operação', 'Internações', 'Ocupação de Leitos'], title: 'Ocupação de Leitos' },
        },
        {
          path: 'Petshop/Hotel/Reservas',
          name: 'petshop-hotel-reservas',
          component: () => import('../pages/petshop/hotel/reservas/ReservaListaPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Hotel', 'Reservas'], title: 'Reservas' },
        },
        {
          path: 'Petshop/Hotel/Reservas/Novo',
          name: 'petshop-hotel-reservas-novo',
          component: () => import('../pages/petshop/hotel/reservas/ReservaNovoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Hotel', 'Reservas', 'Novo'], title: 'Nova reserva' },
        },
        {
          path: 'Petshop/Hotel/Reservas/:id/Editar',
          name: 'petshop-hotel-reservas-editar',
          component: () => import('../pages/petshop/hotel/reservas/ReservaEditarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Hotel', 'Reservas', 'Editar'], title: 'Editar reserva' },
        },
        {
          path: 'Petshop/Hotel/Reservas/:id',
          name: 'petshop-hotel-reservas-visualizar',
          component: () => import('../pages/petshop/hotel/reservas/ReservaVisualizarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Hotel', 'Reservas', 'Visualizar'], title: 'Visualizar reserva' },
        },
        {
          path: 'Petshop/Hotel/Quartos',
          name: 'petshop-hotel-quartos',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Hotel', 'Quartos'], title: 'Quartos' },
        },
        {
          path: 'Petshop/Hotel/Quartos/Eventos',
          name: 'petshop-hotel-quartos-eventos',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Hotel', 'Quartos', 'Eventos de Quarto'], title: 'Eventos de Quarto' },
        },
        {
          path: 'Petshop/Hotel/Monitoramento/Hotel',
          name: 'petshop-hotel-monitoramento-hotel',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Hotel', 'Monitoramento', 'Hotel'], title: 'Monitoramento Hotel' },
        },
        {
          path: 'Petshop/Hotel/Monitoramento/Quartos',
          name: 'petshop-hotel-monitoramento-quartos',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Hotel', 'Monitoramento', 'Quartos'], title: 'Monitoramento Quartos' },
        },
        {
          path: 'Petshop/Creche/Reservas',
          name: 'petshop-creche-reservas',
          component: () => import('../pages/petshop/creche/reservas/ReservaCrecheListaPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Creche', 'Reservas'], title: 'Reservas' },
        },
        {
          path: 'Petshop/Creche/Reservas/Novo',
          name: 'petshop-creche-reservas-novo',
          component: () => import('../pages/petshop/creche/reservas/ReservaCrecheNovoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Creche', 'Reservas', 'Novo'], title: 'Nova reserva' },
        },
        {
          path: 'Petshop/Creche/Reservas/:id/Editar',
          name: 'petshop-creche-reservas-editar',
          component: () => import('../pages/petshop/creche/reservas/ReservaCrecheEditarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Creche', 'Reservas', 'Editar'], title: 'Editar reserva' },
        },
        {
          path: 'Petshop/Creche/Reservas/:id',
          name: 'petshop-creche-reservas-visualizar',
          component: () => import('../pages/petshop/creche/reservas/ReservaCrecheVisualizarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Creche', 'Reservas', 'Visualizar'], title: 'Visualizar reserva' },
        },
        {
          path: 'Petshop/Creche/Turmas',
          name: 'petshop-creche-turmas',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Creche', 'Turmas'], title: 'Turmas' },
        },
        {
          path: 'Petshop/Creche/Turmas/Eventos',
          name: 'petshop-creche-turmas-eventos',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Creche', 'Turmas', 'Eventos de Turma'], title: 'Eventos de Turma' },
        },
        {
          path: 'Petshop/Creche/Monitoramento/Creche',
          name: 'petshop-creche-monitoramento-creche',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Creche', 'Monitoramento', 'Creche'], title: 'Monitoramento Creche' },
        },
        {
          path: 'Petshop/Creche/Monitoramento/Salas',
          name: 'petshop-creche-monitoramento-salas',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Creche', 'Monitoramento', 'Salas'], title: 'Monitoramento Salas' },
        },
        {
          path: 'Petshop/Estetica/Gerenciar',
          name: 'petshop-estetica-gerenciar',
          component: () => import('../pages/petshop/estetica/gerenciar/EsteticaListaPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Estética', 'Gerenciar'], title: 'Gerenciar Estética' },
        },
        {
          path: 'Petshop/Estetica/Gerenciar/Novo',
          name: 'petshop-estetica-gerenciar-novo',
          component: () => import('../pages/petshop/estetica/gerenciar/EsteticaNovoPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Estética', 'Gerenciar', 'Novo'], title: 'Novo atendimento estética' },
        },
        {
          path: 'Petshop/Estetica/Gerenciar/:id/Editar',
          name: 'petshop-estetica-gerenciar-editar',
          component: () => import('../pages/petshop/estetica/gerenciar/EsteticaEditarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Estética', 'Gerenciar', 'Editar'], title: 'Editar atendimento estética' },
        },
        {
          path: 'Petshop/Estetica/Gerenciar/:id',
          name: 'petshop-estetica-gerenciar-visualizar',
          component: () => import('../pages/petshop/estetica/gerenciar/EsteticaVisualizarPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Estética', 'Gerenciar', 'Visualizar'], title: 'Visualizar atendimento estética' },
        },
        {
          path: 'Petshop/Estetica/Pendentes',
          name: 'petshop-estetica-pendentes',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Estética', 'Agendamentos Pendentes'], title: 'Agendamentos Pendentes' },
        },
        {
          path: 'Petshop/Estetica/PendentesAvulso',
          name: 'petshop-estetica-pendentes-avulso',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Estética', 'Agendamentos Avulso Pendentes'], title: 'Agendamentos Avulso Pendentes' },
        },
        {
          path: 'Petshop/Agenda',
          name: 'petshop-agenda',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Agenda'], title: 'Agenda' },
        },
        {
          path: 'Petshop/Administracao/GerenciarPlanos',
          name: 'petshop-admin-gerenciar-planos',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Administração', 'Gerenciar Planos'], title: 'Gerenciar Planos' },
        },
        {
          path: 'Petshop/Administracao/Configuracoes',
          name: 'petshop-admin-configuracoes',
          component: () => import('../pages/petshop/PetshopPlaceholderPage.vue'),
          meta: { breadcrumbs: ['Petshop', 'Administração', 'Configurações'], title: 'Configurações' },
        },

        // Compat: rotas antigas do wizard em 3 páginas
        { path: 'Petshop/NovoPet', redirect: '/Petshop/Pets/Novo' },
        { path: 'Petshop/NovoPet/Caracteristicas', redirect: '/Petshop/Pets/Novo' },
        { path: 'Petshop/NovoPet/Documentos', redirect: '/Petshop/Pets/Novo' },

        { path: 'logout', name: 'logout', component: () => import('../pages/logout/LogoutPage.vue') },
      ],
    },
  ],
})
